export const categories = [
  {
    name: "Phones",
    brands: [
      "iPhone",
      "Samsung",
      "Tecno",
      "Infinix",
      "Oppo",
      "Vivo",
      "Huawei",
      "Nokia",
      "Readme",
      "Xiaomi",
      "OnePlus",
      "Google Pixel",
      "Other",
    ],
  },
  {
    name: "Laptops",
    brands: [
      "HP",
      "Lenovo",
      "Dell",
      "MacBook",
      "Acer",
      "Asus",
      "Microsoft Surface",
      "MSI",
      "Samsung",
      "Razer",
      "Toshiba",
      "Other",
    ],
  },
  {
    name: "Tablets",
    brands: [
      "Samsung",
      "Apple iPad",
      "Huawei",
      "Lenovo",
      "Amazon Fire",
      "Xiaomi Pad",
      "Microsoft Surface",
      "Other",
    ],
  },
  {
    name: "Smart Watches",
    brands: [
      "Apple Watch",
      "Samsung Galaxy Watch",
      "Garmin",
      "Fitbit",
      "Huawei Watch",
      "Xiaomi Mi Band",
      "Amazfit",
      "Fossil",
      "Other",
    ],
  },
  {
    name: "Desktop Computers",
    brands: [
      "Dell",
      "HP",
      "Lenovo",
      "Acer",
      "Asus",
      "Apple iMac",
      "Microsoft Surface Studio",
      "Custom Built",
      "Other",
    ],
  },
  {
    name: "Digital Gadgets",
    brands: [
      "Canon",
      "Sony",
      "GoPro",
      "Nikon",
      "JBL",
      "Smart TV",
      "CCTV Camera",
      "Printer",
      "PlayStation",
      "Other"
    ],
  },
  {
    name: "Computer Accessories",
    brands: [
      "Logitech",
      "Corsair",
      "Razer",
      "HP",
      "Dell",
      "Lenovo",
      "TP-Link",
      "Flash Drive",
      "MS Window Softwares",
      "Other",
      
    ],
  },
];
