export const categories = [
  {
    name: "Phones & Tablets",
    brands: [
      "iPhone",
      "Samsung",
      "Tecno",
      "Infinix",
      "Oppo",
      "Vivo",
      "Huawei",
      "Xiaomi",
      "OnePlus",
      "Google Pixel",
      "Nokia",
      "Realme",
      "iPad",
      "Samsung Galaxy Tab",
      "Other",
    ],
  },
  {
    name: "Laptops & Computers",
    brands: [
      "MacBook",
      "HP",
      "Lenovo",
      "Dell",
      "Acer",
      "Asus",
      "Microsoft Surface",
      "MSI",
      "Razer",
      "Apple iMac",
      "Custom Built",
      "Other",
    ],
  },
  {
    name: "Fashion & Apparel",
    brands: [
      "Nike",
      "Adidas",
      "Zara",
      "H&M",
      "Gucci",
      "Louis Vuitton",
      "Puma",
      "New Balance",
      "Uniqlo",
      "Shein",
      "Ankara Styles",
      "Local Designers",
      "Other",
    ],
  },
  {
    name: "Music & Instruments",
    brands: [
      "Yamaha",
      "Fender",
      "Gibson",
      "Roland",
      "Node Stage",
      "Casio",
      "Korg",
      "Bose",
      "JBL",
      "Sony",
      "Beats by Dre",
      "Audio-Technica",
      "Local Brands",
      "Other",
    ],
  },
  {
    name: "Smart Watches & Wearables",
    brands: [
      "Apple Watch",
      "Samsung Galaxy Watch",
      "Huawei Watch",
      "Garmin",
      "Fitbit",
      "Xiaomi Mi Band",
      "Amazfit",
      "Fossil",
      "TicWatch",
      "Other",
    ],
  },
  {
    name: "Home & Living",
    brands: [
      "IKEA",
      "Philips",
      "Samsung",
      "LG",
      "Hisense",
      "Vitron",
      "Solarmax",
      "Jikokoa",
      "Other",
    ],
  },
  {
    name: "Furniture",
     brands: [
      "IKEA",
      "Ashley Furniture",
      "La-Z-Boy",
      "Wayfair",
      "West Elm",
      "Urban Ladder",
      "Godrej Interio",
      "HomeTown",
      "Local Makers",
      "Other",
    ],
  },
  {
    name: "Beauty & Personal Care",
    brands: [
      "Nivea",
      "L'Oréal",
      "Maybelline",
      "MAC",
      "The Ordinary",
      "CeraVe",
      "Neutrogena",
      "Dove",
      "Local Brands",
      "Other",
    ],
  },
  {
    name: "Sports & Outdoors",
    brands: [
      "Nike",
      "Adidas",
      "Puma",
      "Under Armour",
      "New Balance",
      "Wilson",
      "Decathlon",
      "Other",
    ],
  },
  {
    name: "Automotive & Motorcycle",
    brands: [
      "Toyota",
      "Honda",
      "Suzuki",
      "Yamaha",
      "Bajaj",
      "TVS",
      "Kawasaki",
      "Other",
    ],
  },
  {
    name: "Books & Stationery",
    brands: [
      "Penguin",
      "HarperCollins",
      "Oxford",
      "Cambridge",
      "Local Publishers",
      "Other",
    ],
  },
  {
    name: "Gaming & Consoles",
    brands: [
      "PlayStation",
      "Xbox",
      "Nintendo",
      "Razer",
      "Logitech",
      "Corsair",
      "Other",
    ],
  },
  {
    name: "Other",
    brands: ["Miscellaneous", "Custom", "Other"],
  },
];