export const categories = [
  {
    name: "Phones & Tablets",
    brands: [
      "iPhone",
      "Samsung",
      "Tecno",
      "Infinix",
      "Oppo",
      "Vivo",
      "Huawei",
      "Xiaomi",
      "OnePlus",
      "Google Pixel",
      "Nokia",
      "Realme",
      "Itel",
      "Gionee",
      "iPad",
      "Samsung Galaxy Tab",
      "Lenovo Tab",
      "Huawei MatePad",
      "Other",
    ],
  },
  {
    name: "Laptops & Computers",
    brands: [
      "MacBook",
      "HP",
      "Lenovo",
      "Dell",
      "Acer",
      "Asus",
      "Microsoft Surface",
      "MSI",
      "Razer",
      "Toshiba",
      "Apple iMac",
      "Custom Built",
      "Other",
    ],
  },
  {
    name: "Computer Accessories",
    brands: [
      "Logitech",
      "HP",
      "Dell",
      "Samsung",
      "SanDisk",
      "Seagate",
      "Western Digital",
      "Toshiba",
      "Kingston",
      "Anker",
      "Oraimo",
      "New Age",
      "Generic",
      "Other",
    ],
    subItems: [
      "Printers",
      "Flash Drives",
      "External Hard Drives",
      "Laptop Batteries",
      "Mouse",
      "Keyboards",
      "Monitors",
      "Power Banks",
      "RAM",
      "Webcams",
      "Laptop Bags",
      "Cooling Pads",
    ],
  },
  {
    name: "TVs & Home Entertainment",
    brands: [
      "Samsung",
      "LG",
      "Sony",
      "Hisense",
      "TCL",
      "Vitron",
      "Haier",
      "Philips",
      "Panasonic",
      "Infinix",
      "Skyworth",
      "Other",
    ],
  },
  {
    name: "Home Appliances",
    brands: [
      "LG",
      "Samsung",
      "Hisense",
      "Haier",
      "Philips",
      "Panasonic",
      "Midea",
      "Kenwood",
      "Binatone",
      "Thermocool",
      "Scanfrost",
      "Bruhm",
      "Nexus",
      "Other",
    ],
    subItems: [
      "Refrigerators",
      "Washing Machines",
      "Microwaves",
      "Air Conditioners",
      "Fans",
      "Blenders",
      "Electric Kettles",
      "Cookers",
    ],
  },
  {
    name: "Fashion & Apparel",
    brands: [
      "Nike",
      "Adidas",
      "Zara",
      "H&M",
      "Gucci",
      "Louis Vuitton",
      "Puma",
      "New Balance",
      "Uniqlo",
      "Shein",
      "ASOS",
      "Levi's",
      "Ankara Styles",
      "Local Designers",
      "Aso Oke",
      "Other",
    ],
  },
  {
    name: "Shoes & Footwear",
    brands: [
      "Nike",
      "Adidas",
      "Puma",
      "New Balance",
      "Clarks",
      "Timberland",
      "Crocs",
      "Gucci",
      "Louis Vuitton",
      "Native Shoes",
      "Local Leather",
      "Other",
    ],
  },
  {
    name: "Bags & Luggage",
    brands: [
      "Louis Vuitton",
      "Gucci",
      "Samsonite",
      "American Tourister",
      "Polo",
      "Tommy Hilfiger",
      "Oraimo",
      "Local Leather",
      "School Bags",
      "Other",
    ],
  },
  {
    name: "Jewelry & Watches",
    brands: [
      "Rolex",
      "Casio",
      "Seiko",
      "Citizen",
      "Tissot",
      "Fossil",
      "Michael Kors",
      "Local Beads",
      "Gold/Silver",
      "Other",
    ],
  },
  {
    name: "Beauty & Personal Care",
    brands: [
      "Nivea",
      "L'Oréal",
      "Maybelline",
      "MAC",
      "The Ordinary",
      "CeraVe",
      "Neutrogena",
      "Dove",
      "Garnier",
      "Vaseline",
      "Duduskin",
      "Local Herbal",
      "Other",
    ],
  },
  {
    name: "Health & Wellness",
    brands: [
      "Omron",
      "Beurer",
      "Durex",
      "Always",
      "Pampers",
      "Huggies",
      "Johnson & Johnson",
      "Vitabiotics",
      "Nature's Bounty",
      "Local Herbal",
      "Other",
    ],
  },
  {
    name: "Baby & Kids",
    brands: [
      "Pampers",
      "Huggies",
      "Johnson's",
      "Chicco",
      "Fisher-Price",
      "Lego",
      "Mothercare",
      "Local Toys",
      "Other",
    ],
  },
  {
    name: "Sports & Fitness",
    brands: [
      "Nike",
      "Adidas",
      "Puma",
      "Under Armour",
      "New Balance",
      "Decathlon",
      "York Fitness",
      "Dumbbells & Weights",
      "Yoga Mats",
      "Other",
    ],
  },
  {
    name: "Music & Instruments",
    brands: [
      "Yamaha",
      "Fender",
      "Gibson",
      "Roland",
      "Casio",
      "Korg",
      "Bose",
      "JBL",
      "Sony",
      "Beats by Dre",
      "Audio-Technica",
      "Harman Kardon",
      "Local Drums",
      "Other",
    ],
  },
  {
    name: "Smart Watches & Wearables",
    brands: [
      "Apple Watch",
      "Samsung Galaxy Watch",
      "Huawei Watch",
      "Garmin",
      "Fitbit",
      "Xiaomi",
      "Amazfit",
      "Oraimo",
      "Zeblaze",
      "Other",
    ],
  },
  {
    name: "Gaming & Consoles",
    brands: [
      "PlayStation",
      "Xbox",
      "Nintendo",
      "Razer",
      "Logitech",
      "Corsair",
      "SteelSeries",
      "HyperX",
      "Other",
    ],
  },
  {
    name: "Automotive & Motorcycles",
    brands: [
      "Toyota",
      "Honda",
      "Suzuki",
      "Yamaha",
      "Bajaj",
      "TVS",
      "Kawasaki",
      "BMW",
      "Mercedes",
      "Nissan",
      "Ford",
      "Other",
    ],
  },
  {
    name: "Furniture & Home Decor",
    brands: [
      "IKEA",
      "Ashley Furniture",
      "Wayfair",
      "West Elm",
      "Local Carpenters",
      "Victoria Courts",
      "HomeTown",
      "Godrej Interio",
      "Other",
    ],
  },
  {
    name: "Kitchen & Dining",
    brands: [
      "Philips",
      "Kenwood",
      "Binatone",
      "Moulinex",
      "Pyrex",
      "Vision",
      "Local Pots",
      "Gas Cookers",
      "Other",
    ],
  },
  {
    name: "Books, Stationery & Art",
    brands: [
      "Oxford",
      "Cambridge",
      "Penguin",
      "HarperCollins",
      "Staedtler",
      "Faber-Castell",
      "BIC",
      "Local Publishers",
      "Other",
    ],
  },
  {
    name: "Groceries & Food",
    brands: [
      "Nestlé",
      "Dangote",
      "Indomie",
      "Golden Penny",
      "Peak Milk",
      "Milo",
      "Bournvita",
      "Honeywell",
      "Mama's Pride",
      "Other",
    ],
  },
  {
    name: "Pet Supplies",
    brands: [
      "Pedigree",
      "Whiskas",
      "Royal Canin",
      "Local Feeds",
      "Other",
    ],
  },
  {
    name: "Other",
    brands: ["Miscellaneous", "Custom", "Other"],
  },
];